global:
  resolve_timeout: 5m # Time to wait before marking an alert as resolved after it stops firing.

route:
  group_by: ['alertname'] # Group alerts together if they share the same 'alertname' label.
  group_wait: 10s # BUFFER FOR FIRST ALERT: When a new group is created, wait 10s to collect more alerts before sending the FIRST notification.
  group_interval: 10s # BUFFER FOR UPDATES: If a new alert is added to an existing group (that has already notified), wait 10s before sending an update.
  repeat_interval: 1h # SPAM PROTECTION: If the alert is STILL firing, resend the notification every 1 hour (reminder).
  receiver: 'discord_personal' # <---- Define here your default receiver
  routes:
    - matchers: # Since the alert matches the 'env' and 'alertname' labels defined in prometheus.yml, Alertmanager ignores the default receiver and sends it to 'dev-null'
        - env = "dev"
        - alertname = "InstanceDown"
      receiver: 'dev-null'

receivers:
  - name: 'discord_team'
    discord_configs:
      - webhook_url: ''
        send_resolved: true # Notify when alerts are resolved
        # Customizing the message format
        title: '{{ .CommonLabels.alertname }} ({{ .Status | toUpper }})'
        message: |
          {{ range .Alerts }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          {{ end }}

  - name: 'discord_personal'
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1465456047270531193/ZK_5koy126SSWMRtEmRQSlt_6C0PKKb8cteR_zQgVPmSpT5ywZQMYWYfdTuINzmlyATA' # <--- Paste your personal Discord webhook URL here
        send_resolved: true
        title: '🚨 PERSONAL ALERT: {{ .CommonLabels.alertname }}'
        message: |
          {{ range .Alerts }}
          **Summary:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          {{ end }}

  - name: 'dev-null' # Receiver to drop alerts in development
    webhook_configs:
      - url: 'http://127.0.0.1:1/' # Dummy URL to drop alerts
        send_resolved: true
