apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # Use 'proxy' to route through Grafana server
    url: http://prometheus:9090
    isDefault: true
    editable: false # Prevents accidental changes in UI

  - name: 'Application DB'
    type: frser-sqlite-datasource
    access: proxy
    url: /var/lib/grafana/db-mount/database.db
    isDefault: false
    editable: false