{
 "title": "Transcendence Overview",
 "tags": [ "custom" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend Status",
   "type": "stat",
   "description": "Transcendence is running or not",
   "gridPos": { "h": 3, "w": 15, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ft_transcendence_backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database (SQLite) Status",
   "type": "stat",
   "description": "dummy query (SELECT 1)",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "queryText": "SELECT 1;",
     "rawQueryText": "SELECT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Health and Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU Usage by Container",
   "type": "timeseries",
   "description": "Shows the percentage of CPU resources used by each container. A value of 100% represents full usage of one CPU core. Sudden spikes here often correlate with high latency or heavy processing tasks (like active game calculations).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\"}[5m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Per Container",
   "type": "timeseries",
   "description": "Tracks the Resident Set Size (RSS) memory consumption for each container. This measures the actual physical RAM currently occupied by the process. A constantly rising line (steps) without drops typically indicates a memory leak in the application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "P95 API Latency",
   "type": "timeseries",
   "description": "Measures Server Processing Time. It counts how many requests finished within specific time limits to calculate percentiles (like P95). Does not include network latency",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Active users via Websockets",
   "type": "stat",
   "description": "Total number of users connected via Websockets. User may still be authenticated but not connected via Websocket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "transcendence_connected_users_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Registered Users",
   "type": "stat",
   "description": "Total number of registered users in the database",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "queryText": "SELECT count(*) FROM \"User\";",
     "rawQueryText": "SELECT count(*) FROM \"User\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Most Popular User",
   "type": "stat",
   "description": "The user that has the most friendships",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n  User.alias as \"User\", \n  COUNT(*) as \"Friend Count\"\nFROM (\n  -- Get all people who SENT an accepted request\n  SELECT userId AS id FROM Friendship WHERE status = 'ACCEPTED'\n  UNION ALL\n  -- Get all people who RECEIVED an accepted request\n  SELECT friendId AS id FROM Friendship WHERE status = 'ACCEPTED'\n) AS Friends\nJOIN User ON User.id = Friends.id\nGROUP BY User.alias\nORDER BY \"Friend Count\" DESC\nLIMIT 1;",
     "rawQueryText": "SELECT \n  User.alias as \"User\", \n  COUNT(*) as \"Friend Count\"\nFROM (\n  -- Get all people who SENT an accepted request\n  SELECT userId AS id FROM Friendship WHERE status = 'ACCEPTED'\n  UNION ALL\n  -- Get all people who RECEIVED an accepted request\n  SELECT friendId AS id FROM Friendship WHERE status = 'ACCEPTED'\n) AS Friends\nJOIN User ON User.id = Friends.id\nGROUP BY User.alias\nORDER BY \"Friend Count\" DESC\nLIMIT 1;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Active Remote Matches",
   "type": "timeseries",
   "description": "Total number of remote matches currently ongoing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "transcendence_active_remote_matches_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Page views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Page Views Per Time Range for Authenticated Users",
   "type": "barchart",
   "description": "\"Tracks page views (including refreshes and history navigation) for authenticated users.\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(increase(transcendence_page_views_total{page!~\"login|register\"}[$__range])) by (page)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All-time Page Views",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(transcendence_page_views_total{page!~\"login|register\"}[1y])) by (page))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}